
WITH CTE AS (
SELECT W.ID, WP.AGE, W.COINS_NEEDED, W.POWER, ROW_NUMBER() OVER (PARTITION BY WP.AGE, W.POWER ORDER BY W.COINS_NEEDED) AS ROWN FROM WANDS W
INNER JOIN WANDS_PROPERTY WP ON W.CODE = WP.CODE
WHERE WP.IS_EVIL = 0
) SELECT CTE.ID, CTE.AGE, CTE.COINS_NEEDED, CTE.POWER FROM CTE
WHERE CTE.ROWN = 1
ORDER BY CTE.POWER DESC, CTE.AGE DESC
